-- Extend audit coverage for user, asset supporting records, and Knowledge Base changes.
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_USER';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_ASSET_NOTE';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_ASSET_NOTE';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_ASSET_NOTE';
ALTER TYPE "AuditAction" ADD VALUE 'UPLOAD_ASSET_ATTACHMENT';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_ASSET_ATTACHMENT';
ALTER TYPE "AuditAction" ADD VALUE 'DOWNLOAD_ASSET_ATTACHMENT';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_KB_CATEGORY';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_KB_CATEGORY';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_KB_DOCUMENT';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_KB_DOCUMENT';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_KB_DOCUMENT';
ALTER TYPE "AuditAction" ADD VALUE 'UPLOAD_KB_IMAGE';
