version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: it-asset-db
    environment:
      POSTGRES_USER: infrapilot
      POSTGRES_PASSWORD: AssetOpsPostgres2026!
      POSTGRES_DB: infrapilot_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
